service: p5-mailing-service
provider:
  name: aws
  runtime: nodejs12.x

stage: dev
region: sa-east-1

plugins:
  - serverless-offline

functions:
  consulta:
    handler: dist/handler.consulta
    events:
      - http:
          path: /landing/consulta
          method: post
  preinscripcion:
    handler: dist/handler.preinscripcion
    events:
      - http:
          path: landing/aplicar
          method: post
